---
- name: "Install the necessary packages from Grafana"
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: present

- name: "Add Grafana GPG key"
  become: true
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: "Add the Grafana repository"
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: "Run apt update and upgrade"
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    state: present

- name: "Install Grafana"
  become: true
  ansible.builtin.apt:
    name:
      - grafana
    state: present

- name: "Enable and start the Grafana Service"
  become: true
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: started
