---
- name: "Download and extract Prometheus"
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/\
      v3.5.1/prometheus-3.5.1.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true

- name: "Create installation directory"
  become: true
  ansible.builtin.file:
    path: /opt/prometheus/
    state: directory

- name: "Create prometheus system user"
  become: true
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: /sbin/nologin

- name: "Copy config files"
  become: true
  ansible.builtin.copy:
    src: /tmp/prometheus-3.5.1.linux-amd64/
    dest: /opt/prometheus/
    remote_src: true

- name: "Set directory permissions for prometheus user"
  become: true
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    recurse: true

- name: "Copy systemd service for prometheus"
  become: true
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: "Start and enable service"
  become: true
  ansible.builtin.service:
    name: prometheus.service
    state: started
    enabled: true
    daemon_reload: true
