---
name: PyLint
on: [push, pull_request]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: src
          python-version: 3.11
